Add templating of disk partitioning based on OSA node roles
Remove cinder_loopback call from osa-nodes-configure-system playbook
Fix cinder_loopback for proper idempotency

diff --git a/ansible/tasks/disk_partition_create.yml b/ansible/tasks/disk_partition_create.yml
--- a/ansible/tasks/disk_partition_create.yml
+++ b/ansible/tasks/disk_partition_create.yml
@@ -5,8 +5,11 @@
 
 - fail: msg="Wrong partition specification {{ partition_setup }}"
   when: (partition_setup is not defined or not partition_setup.get('name')
-         or not partition_setup.get('size') or not (partition_setup.get('mountpoint')
-         or partition_setup.get('type') == 'swap'))
+         or not partition_setup.get('size') or not partition_setup.get('vg')
+         or not (
+           partition_setup.get('mountpoint')
+           or partition_setup.get('type') == 'vgonly'
+           or partition_setup.get('type') == 'swap'))
 
 - name: Retrieving current partitions infos
   parted:
@@ -20,134 +23,150 @@
   set_fact:
     found_disk_partitions: "{{ partitions_infos.get('partitions', []) }}"
     found_disk_size: "{{ partitions_infos.get('disk', {}).get('size') }}"
+    partition_roles: "{{ partition_setup.get('roles', []) }}"
+#    node_roles: "{{ hostvars[inventory_hostname].get('ansible_local', {}).get() }}"
 
-- name: Setting facts for non-partitioned disk
+- name: Setting partitions role facts
   set_fact:
-    existing_partition: []
-    last_partition_id: 0
-    partitions_size: 0.0
-  when: found_disk_partitions | length == 0
+    is_partition_for_all_roles: "{{ (partition_roles | length == 0) | bool }}"
+    is_role_match: "{{ ((partition_roles | json_query('[*].keys(@)') | flatten | intersect(input_node_roles)) | length > 0) | bool }}"
 
-- name: Looking if partition {{ partition_setup.get('name') }} already exits
+- name: Setting partitions role final test facts
   set_fact:
-    existing_partition: "{{ found_disk_partitions | selectattr('name', 'match', '^' + partition_setup.get('name') + '$') | list }}"
-    last_partition_id: "{{ found_disk_partitions | map(attribute='num') | list | max }}"
-    partitions_size: "{{ found_disk_partitions | map(attribute='size') | list | sum }}"
-  when: found_disk_partitions | length > 0
+    is_to_be_done: "{{ is_partition_for_all_roles or is_role_match | bool }}"
 
-- name: Setting extra derived disk and partitions facts for non-partitioned disk
-  set_fact:
-    last_partition_infos:
-      - { 'end': 0.0 }
-    remaining_disk_size: "{{ found_disk_size | float }}"
-  when: found_disk_partitions | length == 0
+- block:
+  - name: Setting facts for non-partitioned disk
+    set_fact:
+      existing_partition: []
+      last_partition_id: 0
+      partitions_size: 0.0
+    when: found_disk_partitions | length == 0
 
-- name: Setting extra derived disk and partitions facts
-  set_fact:
-    last_partition_infos: "{{ found_disk_partitions | selectattr('num', 'equalto', last_partition_id | int ) | list }}"
-    remaining_disk_size: "{{ (found_disk_size | float) - (partitions_size | float) }}"
-  when: found_disk_partitions | length > 0
+  - name: Setting facts in case partition {{ partition_setup.get('name') }} already exits
+    set_fact:
+      existing_partition: "{{ found_disk_partitions | selectattr('name', 'match', '^' + partition_setup.get('name') + '$') | list }}"
+      last_partition_id: "{{ found_disk_partitions | map(attribute='num') | list | max }}"
+      partitions_size: "{{ found_disk_partitions | map(attribute='size') | list | sum }}"
+    when: found_disk_partitions | length > 0
 
-- fail: msg="Number of last partition found should always be 1"
-  when: last_partition_infos | length != 1 and found_disk_partitions | length > 0
+  - name: Setting extra derived disk and partitions facts for non-partitioned disk
+    set_fact:
+      last_partition_infos:
+        - { 'end': 0.0 }
+      remaining_disk_size: "{{ found_disk_size | float }}"
+    when: found_disk_partitions | length == 0
 
-- fail: msg="Not enough space remaining on disk for partition {{ partition_setup.get('name') }} required {{ partition_setup.get('size') }} remaining {{ remaining_disk_size }}"
-  when: existing_partition | length == 0 and remaining_disk_size | float < partition_setup.get('size') | float
+  - name: Setting extra derived disk and partitions facts
+    set_fact:
+      last_partition_infos: "{{ found_disk_partitions | selectattr('num', 'equalto', last_partition_id | int ) | list }}"
+      remaining_disk_size: "{{ (found_disk_size | float) - (partitions_size | float) }}"
+    when: found_disk_partitions | length > 0
 
-- name: Creating partition {{ partition_setup.get('name') }}
-  parted:
-    device: "{{ disk_device }}"
-    state: present
-    unit: GB
-    name: "{{ partition_setup.get('name') }}"
-    label: gpt
-    flags: [ lvm ]
-    align: optimal
-    number: "{{ last_partition_id | int + 1 }}"
-    part_start: "{{ last_partition_infos[0].get('end') | float }}GB"
-    part_end: "{{ last_partition_infos[0].get('end') | float + partition_setup.get('size') | float }}GB"
-  environment: "{{ parted_env | default({}) | combine({ 'LC_ALL': 'C' }) }}"
-  when: existing_partition | length == 0
+  - fail: msg="Number of last partition found should always be 1"
+    when: last_partition_infos | length != 1 and found_disk_partitions | length > 0
 
-- name: Setting PV name
-  set_fact:
-    target_pv: "{{ partition_setup.get('vg', '') }}{{ partition_setup.get('lv', '') }}"
+  - fail: msg="Not enough space remaining on disk for partition {{ partition_setup.get('name') }} required {{ partition_setup.get('size') }} remaining {{ remaining_disk_size }}"
+    when: existing_partition | length == 0 and remaining_disk_size | float < partition_setup.get('size') | float
 
-- name: Setting partition device (empty disk)
-  set_fact:
-    target_partition: "{{ disk_device }}{{ last_partition_id | int + 1 }}"
-    partition_id: "{{ last_partition_id | int + 1 }}"
-  when: existing_partition | length == 0
+  - name: Creating partition {{ partition_setup.get('name') }}
+    parted:
+      device: "{{ disk_device }}"
+      state: present
+      unit: GB
+      name: "{{ partition_setup.get('name') }}"
+      label: gpt
+      flags: [ lvm ]
+      align: optimal
+      number: "{{ last_partition_id | int + 1 }}"
+      part_start: "{{ last_partition_infos[0].get('end') | float }}GB"
+      part_end: "{{ last_partition_infos[0].get('end') | float + partition_setup.get('size') | float }}GB"
+    environment: "{{ parted_env | default({}) | combine({ 'LC_ALL': 'C' }) }}"
+    when: existing_partition | length == 0
 
-- name: Setting partition device
-  set_fact:
-    target_partition: "{{ disk_device }}{{ existing_partition[0].get('num') }}"
-    partition_id: "{{ existing_partition[0].get('num') }}"
-  when: existing_partition | length > 0
+  - name: Setting PV name
+    set_fact:
+      target_pv: "{{ partition_setup.get('vg', '') }}{{ partition_setup.get('lv', '') }}"
 
-- name: Creating associated physical volume
-  lvg:
-    pvs: "{{ target_partition }}"
-    vg: "{{ target_pv }}"
-    state: present
-  register: pv_status
+  - name: Setting partition device (empty disk)
+    set_fact:
+      target_partition: "{{ disk_device }}{{ last_partition_id | int + 1 }}"
+      partition_id: "{{ last_partition_id | int + 1 }}"
+    when: existing_partition | length == 0
 
-- name: Creating associated logical volume
-  lvol:
-    pvs: "{{ target_partition }}"
-    vg: "{{ target_pv }}"
-    lv: "{{ partition_setup.get('lv') }}"
-    size: '100%FREE'
-    state: present
-  when: pv_status is changed
-  register: lv_status
+  - name: Setting partition device
+    set_fact:
+      target_partition: "{{ disk_device }}{{ existing_partition[0].get('num') }}"
+      partition_id: "{{ existing_partition[0].get('num') }}"
+    when: existing_partition | length > 0
 
-- name: Formating {{ target_partition }} partition as {{ partition_setup.get('fstype', 'xfs') }}
-  filesystem:
-    dev: "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
-    fstype: "{{ partition_setup.get('fstype', 'xfs') }}"
-    force: "{{ partition_setup.get('type') == 'swap' | bool }}"
-  when: partition_setup.get('type') != 'swap' and existing_partition | length == 0 and lv_status is changed
+  - name: Creating associated physical volume
+    lvg:
+      pvs: "{{ target_partition }}"
+      vg: "{{ target_pv }}"
+      state: present
+    register: pv_status
 
-- name: Creating mount points, fstab entries and mount the filesystem for {{ target_partition }}
-  mount:
-    name: "{{ partition_setup.get('mountpoint') }}"
-    src: "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
-    fstype: "{{ partition_setup.get('fstype', 'xfs') }}"
-    state: mounted
-  when: partition_setup.get('mountpoint')
+  - name: Creating associated logical volume
+    lvol:
+      pvs: "{{ target_partition }}"
+      vg: "{{ target_pv }}"
+      lv: "{{ partition_setup.get('lv') }}"
+      size: '100%FREE'
+      state: present
+    when: pv_status is changed and partition_setup.get('type') != 'vgonly'
+    register: lv_status
 
-- name: Format the swap partition
-  command: "mkswap /dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
-  when: partition_setup.get('type') == 'swap' and existing_partition | length == 0
+  - name: Formating {{ target_partition }} partition as {{ partition_setup.get('fstype', 'xfs') }}
+    filesystem:
+      dev: "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
+      fstype: "{{ partition_setup.get('fstype', 'xfs') }}"
+      force: "{{ partition_setup.get('type') == 'swap' | bool }}"
+    when: partition_setup.get('type') != 'vgonly' and partition_setup.get('type') != 'swap' and existing_partition | length == 0 and lv_status is changed
 
-- name: Ensure that the swap partition entry is in /etc/fstab
-  mount:
-    name: none
-    src: "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
-    fstype: swap
-    opts: sw
-    passno: 0
-    dump: 0
-    state: present
-  when: partition_setup.get('type') == 'swap'
+  - name: Creating mount points, fstab entries and mount the filesystem for {{ target_partition }}
+    mount:
+      name: "{{ partition_setup.get('mountpoint') }}"
+      src: "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
+      fstype: "{{ partition_setup.get('fstype', 'xfs') }}"
+      state: mounted
+    when: partition_setup.get('mountpoint')
 
-- name: Bring swap file online
-  shell: |
-    return_code=0
-    if ! grep "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}" /proc/swaps; then
-      swapon "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
-      return_code=2
-    fi
-    exit ${return_code}
-  register: _set_swap_online
-  changed_when: _set_swap_online.rc == 2
-  failed_when: _set_swap_online.rc not in [0, 2]
-  when: partition_setup.get('type') == 'swap'
+  - name: Format the swap partition
+    command: "mkswap /dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
+    when: partition_setup.get('type') == 'swap' and existing_partition | length == 0
 
-- name: Set system swappiness
-  sysctl:
-    name: vm.swappiness
-    value: 10
-    state: present
-  when: partition_setup.get('type') == 'swap'
+  - name: Ensure that the swap partition entry is in /etc/fstab
+    mount:
+      name: none
+      src: "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
+      fstype: swap
+      opts: sw
+      passno: 0
+      dump: 0
+      state: present
+    when: partition_setup.get('type') == 'swap'
+
+  - name: Bring swap file online
+    shell: |
+      return_code=0
+      if ! grep "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}" /proc/swaps; then
+        swapon "/dev/{{ target_pv }}/{{ partition_setup.get('lv') }}"
+        return_code=2
+      fi
+      exit ${return_code}
+    register: _set_swap_online
+    changed_when: _set_swap_online.rc == 2
+    failed_when: _set_swap_online.rc not in [0, 2]
+    when: partition_setup.get('type') == 'swap'
+
+  - name: Set system swappiness
+    sysctl:
+      name: vm.swappiness
+      value: 10
+      state: present
+    when: partition_setup.get('type') == 'swap'
+  when: is_to_be_done | bool == True
+
+- debug: msg="Not creating partition {{ partition_setup.get('name') }} Node roles {{ input_node_roles }} Partition roles {{ partition_roles }}"
+  when: is_to_be_done | bool == False
